name: Run-Daily

on:
  schedule:
    - cron: '0 8,12,16,0 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions: 
    - contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Run Script
      run: |
        cd pages/
        chmod +x get-sources.sh
        ./get-sources.sh
    
    - name: Commit and Push
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update $(date +%Y-%m-%d)" && git push)
