name: Run-Daily

on:
  schedule:
    - cron: '0 8,12,16,0 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2 
    - name: Run Script
      run: |
        cd pages/
        chmod +x get-sources.sh
        ./get-sources.sh
